name: Conectados Server Deployment

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: ./server
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server/**  # Upload the *contents* of server directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_620196E27C3E40B792C0D6AE7E5A41AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_92F35518CE3844ADB58310C0F25C12B4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_03D78AD761EF454DB450DC5A54E7CCD7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ConectadosE7'
          slot-name: 'Production'
          package: .  # Deploy current directory, where downloaded artifact contents now exist

  selenium-tests:
    runs-on: ubuntu-latest
    needs: deploy  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Selenium test dependencies
        working-directory: ./selenium
        run: npm install

      - name: Run Selenium tests
        working-directory: ./selenium
        run: |
          set -e
          EXIT_CODE=0
          for TEST in Home.test.js Services.test.js Register.test.js Login.test.js; do
            echo "Running $TEST..."
            node $TEST || EXIT_CODE=1
            sleep 10
          done
          exit $EXIT_CODE
        
